name: CI_Card_Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: go test -v ./...

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'latest'